string nome, especie, pelecor, raca;
int idade;
Console.WriteLine("House Pet");
Console.WriteLine("Insira o nome do animal: ");
nome = Console.ReadLine()!;
Console.WriteLine("Insira a especie do animal:");
especie = Console.ReadLine()!;
Console.WriteLine("Insira a raça do animal:");
raca = Console.ReadLine()!;
Console.WriteLine("Insira a pelaem/cor do animal:");
pelecor = Console.ReadLine()!;
Console.WriteLine("Insira a idade do animal:");
idade = Convert.ToInt32(Console.ReadLine()!);
Console.WriteLine ("========================================");
Console.WriteLine("|Pet Hotel: House Pet|".PadLeft(31, '.').PadRight(40, '.'));
Console.WriteLine ("========================================");
Console.Write ($"|Espécie:{especie}|".PadRight(20, '.'));
Console.WriteLine ($"|Raça:{raca}|".PadLeft(20, '.'));
Console.WriteLine ("========================================");
Console.WriteLine ($"Atende pelo nome de: {nome}");
Console.Write ($"|Idade:{idade}|".PadRight(20, '.'));
Console.WriteLine ($"|Pelaem/Cor:{pelecor}|".PadLeft(20, '.'));
Console.WriteLine ("========================================");